config/routes.rb
AjaxTutor::Application.routes.draw do
  get "persons_controller/show"

  get "manual_ajax/link"

  get "rails_magic/link"
  get "rails_magic/form"

  post 'rails_magic/delete_smth'
  post 'rails_magic/create_smth'
  get 'rails_magic/play_with_request'

  get 'manual_ajax/content_for_link'
  get 'manual_ajax/some_special_content_for_link'

  resource :persons, only: [:show]

  root :to => 'home#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :last_name, :first_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/manual_ajax_controller.rb
class ManualAjaxController < ApplicationController
  def link
    gon.special_url = manual_ajax_some_special_content_for_link_path
  end

  def content_for_link
  end

  def some_special_content_for_link
    secret_html = render_to_string('some_special_content_for_link')
    render html: secret_html
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  respond_to :html, :json

  def show
    @person = Person.first
    @person.touch

    respond_with(@person)
  end

  #def show
  #  @user = Person.first
  #  respond_with(@user) do |format|
  #    format.html { render }
  #    format.json { render json: @user }
  #  end
  #end
end

app/controllers/rails_magic_controller.rb
# encoding: utf-8
class RailsMagicController < ApplicationController
  def link
  end

  def form
  end

  def delete_smth
    render nothing: true, status: 200
  end

  def create_smth
    render text: "Добры вечар!"
  end

  def play_with_request
    if request.xhr?
      render js: "alert('hello');"
    else

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manual_ajax_helper.rb
module ManualAjaxHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/rails_magic_helper.rb
module RailsMagicHelper
end

app/views/home/index.html.erb
<h1>Rails magic</h1>
<ul>
  <li><%= link_to "Ссылки с ajax", rails_magic_link_url %></li>
  <li><%= link_to "Формы с ajax", rails_magic_form_url  %></li>
  <li><%= link_to "Поиграемся с реквестом", rails_magic_play_with_request_url %></li>
</ul>

<h1>Manual handling</h1>
<ul>
  <li><%= link_to "HTML с ajax руками", manual_ajax_link_url %></li>
  <li><%= link_to "JSON и темплейты", persons_url %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTutor</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/manual_ajax/content_for_link.html.erb
<h1 class="eye_destroyer">Здравствуй, дружище!</h1>

app/views/manual_ajax/link.html.erb
<div>
  <%= link_to 'Жмак', '#', class: 'touch_me_baby' %>
</div>

<div>
  <%= link_to 'А теперь нечто особенное!', '#', class: 'smth_special' %>
</div>

app/views/manual_ajax/some_special_content_for_link.html.erb
<%= image_tag 'splash-cold-water1.png' %>

app/views/persons/show.html.erb
<div class="person_info">

  <h2>Персона №<%= @person.id %> <a href="#" class="close_btn">[X]</a></h2>

  <h3><%= [@person.first_name, @person.last_name].join ' ' %></h3>
  <span>Последний раз мы трогали эту персону в <%= @person.updated_at %></span>
</div>

<%= link_to "Обновить", "#", class: "refresh_info" %>

app/views/rails_magic/_good_morning.html.erb
<h1>Добры вечар! (:{)</h1>

app/views/rails_magic/create_smth.js.erb
$(".magic_form_container").html("<%= escape_javascript(render(partial: 'good_morning', layout: false)) %>");

app/views/rails_magic/form.html.erb
<div class="magic_form_container">
  <%= form_tag rails_magic_create_smth_url, remote: true do %>
    <%= text_field_tag :first_name, "Александр" %>
    <%= text_field_tag :last_name, "Лукашенко" %>
    <%= submit_tag "Тынц!" %>
  <% end %>
</div>

app/views/rails_magic/link.html.erb
<%= link_to "Удалить все!", rails_magic_delete_smth_path, method: :post, remote: true %>

app/views/rails_magic/play_with_request.html.erb
<%= link_to "Тырц", rails_magic_play_with_request_url, method: :get, remote: true %>